server:
  port: 8080
  servlet:
    context-path: /lvtu
spring:
  resources:
    static-locations: file:D:/lvtu
  datasource:
    url: jdbc:mysql://localhost:3306/lvtu?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=UTF-8
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
  jpa:
    database: mysql
    show-sql: true
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 30000s
    lettuce:
      pool:
        max-active: 8
        max-wait: 60000ms
        max-idle: 8
        min-idle: 0
spring.servlet.multipart.max-file-size: 1024MB
spring.servlet.multipart.max-request-size: 1024MB
#upload.path: D:\Upload
# 开启 MyBatis-Plus SQL 打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

